syntax on
set number
set relativenumber
set tabstop=4
set shiftwidth=4
set expandtab
set mouse=a
set autoindent
set smartindent
set hlsearch
set incsearch
set ignorecase
set smartcase
set wrap
set showmatch
set laststatus=2
set clipboard=unnamedplus
set noswapfile
set timeoutlen=500
set encoding=utf-8
