#!/usr/bin/env bash

search_paths=(
	"$HOME/personal/"
	"$HOME/personal/experiment/"
	"$HOME/personal/tmp/"
	"$HOME/scripts/"
	"$HOME/Downloads/"
	"$HOME/hackathons/"
	"$HOME/work/"
	"$HOME/.config/"
	"$HOME/.tmux/"
	"$HOME/Documents/GitHub/"
	"$HOME/Pictures/screenshots/"
	"$HOME/.lazyffmpeg/"
)

if [[ $# -eq 1 ]]; then
	selected="$1"
else
	selected=$(find "${search_paths[@]}" -mindepth 0 -maxdepth 1 -type d 2>/dev/null | fzf)
fi

if [[ -z "$selected" ]]; then
	exit 0
fi

code "$selected"
